name: redismajids
version: 0.1
summary: say hello to the world
description: |
  This is a basic make snap. It just prints a hello world.
confinement: strict
grade: devel
base: core18

build-packages: [gcc, libc6-dev]

apps:
  make-hello:
    command: test

parts:
  make-project:
    source: .
    plugin: make
