name: snapcraft
base: core
summary: easily create snaps
description: |
    Snapcraft aims to make upstream developers' lives easier and as such is not
    a single toolset, but instead is a collection of tools that enable the
    natural workflow of an upstream to be extended with a simple release step
    into Snappy.
adopt-info: snapcraft
confinement: classic

apps:
  snapcraft:
    command: bin/snapcraft
    completer: snapcraft-completion

build-packages:
  - wget
